export default {
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    FETCH_USER_BY_ID: "FETCH_USER_BY_ID",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
	DELETE_USER: "DELETE_USER",


    USERS_REQUEST: "USERS_REQUEST",
    USERS_RESPONSE: "USERS_RESPONSE",
    USERS_ERROR: "USERS_ERROR",
    ONE_USER_RESPONSE: "ONE_USER_RESPONSE",
	DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
	DELETE_USER_ERROR: "DELETE_USER_ERROR",

    CURRENT_USER_REQUEST: "CURRENT_USER_REQUEST",
    CURRENT_USER_RESPONSE: "CURRENT_USERRESPONSE",
    CURENT_USER_ERROR: "CURRENT_USER_ERROR",
};
