export default {
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    FETCH_USER_BY_ID: "FETCH_USER_BY_ID",


    TEST: "TEST",
    USERS_REQUEST: "USERS_REQUEST",
    USERS_RESPONSE: "USERS_RESPONSE",
    USERS_ERROR: "USERS_ERROR",
    ONE_USER_RESPONSE: "ONE_USER_RESPONSE"
};
